import { useState } from "react";
import { Link } from "@tanstack/react-router";
import type { Lesson } from "~/data/latinLessons";
import type { PronMode } from "~/lib/pronunciation";
import type { LessonProgress } from "~/engine/progress";
import NavBar from "~/components/NavBar";
import PronunciationToggle from "~/components/PronunciationToggle";
import Bookshelf, { UNIT_MAP } from "~/components/Bookshelf";

interface Props {
  lessons: Lesson[]; unlockedLessons: number; onSelectLesson: (idx: number) => void;
  onOpenDrill: () => void; onOpenPlacement: () => void; onOpenAIPractice: (lessonId: number) => void;
  onPronModeChange: (mode: PronMode) => void;
  // Optional until the route integration phase wires them in (keeps build green).
  onOpenSettings?: () => void; onOpenAudio?: () => void; onOpenProgress?: () => void; onOpenReview?: () => void; onOpenExplore?: () => void; devMode?: boolean;
  // Language-parameterized copy (English route passes its own; defaults keep Latin byte-identical).
  title?: string; description?: string; emoji?: string; showPronToggle?: boolean; showAIPractice?: boolean; backTo?: string;
  // Per-book progress for shelf bookmark tabs (route passes loadProgress(language.id)).
  lessonProgress?: LessonProgress[];
}
export default function LessonMenu({lessons,unlockedLessons,onSelectLesson,onOpenDrill,onOpenPlacement,onOpenAIPractice,onPronModeChange,onOpenSettings,onOpenAudio,onOpenProgress,onOpenReview,onOpenExplore,devMode=false,title="Latin 101",description="Master Latin grammar through bite-sized, interactive lessons — from first declension through passive voice, following Henle's <em>First Year Latin</em>.",emoji="🏛️",showPronToggle=true,showAIPractice=true,backTo="/",lessonProgress}: Props) {
  // English fallback: lesson ids 2001–2010 match zero UNIT_MAP shelves, so the
  // shelf view is unavailable → default to TOC and hide the toggle (English
  // route stays byte-identical; no English route change needed).
  const shelfMatches = UNIT_MAP.some((u) => lessons.some((l) => l.id >= u.startId && l.id <= u.endId));
  const [view, setView] = useState<"shelf" | "toc">(shelfMatches ? "shelf" : "toc");
  const effectiveView: "shelf" | "toc" = shelfMatches ? view : "toc";
 return <div className="min-h-dvh flex flex-col"><NavBar /><main className="flex-1 px-4 py-8 sm:py-12"><div className="mx-auto max-w-2xl">
  <div className="text-center mb-10"><span className="text-5xl mb-4 block">{emoji}</span><div className="flex items-center justify-center gap-2"><h1 className="text-3xl font-extrabold text-burgundy-900 sm:text-4xl">{title}</h1>{devMode&&<span className="rounded-full border border-amber-400 bg-amber-100 px-2.5 py-1 text-[11px] font-black tracking-wider text-amber-800">DEV</span>}</div><p className="mt-3 text-gray-600 leading-relaxed max-w-md mx-auto" dangerouslySetInnerHTML={{__html:description}}/></div>
  <div className="mb-4 flex items-stretch gap-2 sm:gap-3"><div className="grid flex-1 gap-2 sm:grid-cols-3 sm:gap-3"><button onClick={onOpenDrill} className="w-full rounded-2xl bg-gold-400 py-4 text-lg font-black text-burgundy-950 shadow-lg transition hover:bg-gold-300 hover:shadow-xl">🗡️ Drill</button><button onClick={onOpenPlacement} className="w-full rounded-2xl border-2 border-gold-600 bg-cream-50 py-4 text-lg font-black text-burgundy-800 shadow transition hover:bg-gold-50 hover:shadow-lg">📋 Placement</button>{onOpenAudio&&<button onClick={onOpenAudio} className="w-full rounded-2xl border-2 border-burgundy-200 bg-cream-50 py-4 text-lg font-black text-burgundy-800 shadow">🎧 Listen</button>}{onOpenProgress&&<button onClick={onOpenProgress} className="w-full rounded-2xl border-2 border-burgundy-200 bg-cream-50 py-4 text-lg font-black text-burgundy-800 shadow">📊 Progress</button>}{onOpenReview&&<button onClick={onOpenReview} className="w-full rounded-2xl border-2 border-burgundy-200 bg-cream-50 py-4 text-lg font-black text-burgundy-800 shadow">🔍 Review</button>}{showAIPractice&&<button onClick={()=>onOpenAIPractice(1)} className="w-full rounded-2xl bg-purple-100 border-2 border-purple-300 py-4 text-lg font-black text-purple-800 shadow transition hover:bg-purple-200 hover:shadow-lg">🤖 AI Practice</button>}</div>{onOpenSettings&&<button onClick={onOpenSettings} title="Settings" aria-label="Settings" className="flex w-14 shrink-0 items-center justify-center rounded-2xl border-2 border-gray-300 bg-white text-xl text-gray-500 shadow transition hover:border-gray-400 hover:bg-cream-50 hover:text-burgundy-700">⚙️</button>}</div>
  {onOpenExplore&&<button onClick={onOpenExplore} className="w-full rounded-2xl border-2 border-gold-400 bg-gold-50 p-4 text-left shadow-sm transition hover:bg-gold-100 hover:shadow-md"><div className="flex items-center gap-3"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-gold-400 text-xl text-burgundy-950">🏛️</span><div className="flex-1 min-w-0"><h3 className="font-bold text-burgundy-900">Explore Latin</h3><p className="text-sm text-gray-500 mt-0.5">Optional enrichment lessons on Roman life, culture, and review</p></div><svg className="h-5 w-5 text-gold-700 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M9 5l7 7-7 7"/></svg></div></button>}
  {showPronToggle&&<div className="flex justify-center mb-6"><PronunciationToggle onChange={onPronModeChange}/></div>}
  {shelfMatches&&<div className="mb-6 flex justify-center"><div role="group" aria-label="Lesson list view" className="inline-flex rounded-2xl border-2 border-gold-600 bg-cream-50 p-1 shadow-sm"><button type="button" aria-pressed={effectiveView==="shelf"} onClick={()=>setView("shelf")} className={`rounded-xl px-4 py-2 text-sm font-black transition ${effectiveView==="shelf"?"bg-gold-500 text-burgundy-950 shadow":"text-burgundy-800 hover:bg-gold-100"}`}>📚 Bookshelf</button><button type="button" aria-pressed={effectiveView==="toc"} onClick={()=>setView("toc")} className={`rounded-xl px-4 py-2 text-sm font-black transition ${effectiveView==="toc"?"bg-gold-500 text-burgundy-950 shadow":"text-burgundy-800 hover:bg-gold-100"}`}>📋 Table of Contents</button></div></div>}
  {effectiveView==="shelf"?<Bookshelf lessons={lessons} unlockedLessons={unlockedLessons} lessonProgress={lessonProgress} onSelectLesson={onSelectLesson}/>:<LessonTOC lessons={lessons} unlockedLessons={unlockedLessons} onSelectLesson={onSelectLesson} showAIPractice={showAIPractice} onOpenAIPractice={onOpenAIPractice}/>}
  <div className="mt-10 text-center"><Link to={backTo} className="text-sm text-gray-400 hover:text-burgundy-600 transition">← Back to {backTo === "/" ? "Verbum" : "Languages"}</Link></div>
 </div></main></div>;
}

/** Today's flat lesson list, extracted verbatim from the menu (TOC view). */
function LessonTOC({lessons,unlockedLessons,onSelectLesson,showAIPractice,onOpenAIPractice}:{lessons:Lesson[];unlockedLessons:number;onSelectLesson:(idx:number)=>void;showAIPractice:boolean;onOpenAIPractice:(lessonId:number)=>void}) {
 return <div className="space-y-3">{lessons.map((l,i)=>{const locked=i>=unlockedLessons;return <button key={l.id} onClick={()=>onSelectLesson(i)} disabled={locked} className={`w-full text-left rounded-2xl border-2 p-5 transition-all duration-200 ${locked?"border-gray-200 bg-gray-50 opacity-50 cursor-not-allowed":"border-burgundy-200 bg-white hover:border-burgundy-400 hover:shadow-md cursor-pointer"}`}><div className="flex items-start gap-4"><div className={`flex h-10 w-10 items-center justify-center rounded-xl shrink-0 text-lg font-bold ${locked?"bg-gray-200 text-gray-400":"bg-burgundy-100 text-burgundy-700"}`}>{locked?"🔒":l.id}</div><div className="flex-1 min-w-0"><h3 className={`font-bold text-base ${locked?"text-gray-400":"text-burgundy-900"}`}>Lesson {l.id}: {l.title}</h3>{l.subtitle&&<p className="text-sm text-gray-500 mt-0.5">{l.subtitle}</p>}<p className="text-xs text-gray-400 mt-1">{l.exercises.length} exercises</p>{!locked&&showAIPractice&&<span role="button" tabIndex={0} onClick={e=>{e.stopPropagation();onOpenAIPractice(l.id)}} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();e.stopPropagation();onOpenAIPractice(l.id)}}} className="mt-2 inline-flex items-center gap-1 text-xs font-medium text-purple-600 hover:text-purple-800 bg-purple-50 hover:bg-purple-100 px-2 py-0.5 rounded-full transition">🤖 Practice</span>}</div>{!locked&&<svg className="h-5 w-5 text-burgundy-400 shrink-0 mt-2" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M9 5l7 7-7 7"/></svg>}</div></button>})}</div>;
}
